<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Dependents</name>
  <uuid>5b595380-e824-4741-8a57-60c1196f7287</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Client is Dependents
then
	add 1 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
