<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>genAIPolicyReccomendataionTest</name>
  <uuid>c70247e1-c838-4584-b85a-4abff22cad2e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated token count of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
