<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>genAIPolicyReccomendataionTest</name>
  <uuid>ef3201b3-6f16-4be5-8ade-94a8ccab7f41</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the generated text of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
