<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>genAIPolicyReccomendataionTest</name>
  <uuid>79ca16a2-30a6-4180-be99-f1182dbfdb2b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the stop reason of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
