<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>genAIPolicyReccomendataionTest</name>
  <uuid>bb7f39d1-02e3-47f5-b0a6-aacd26b75f62</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the policy is Policy , 
		the age is Age , 
		the dependents is Dependents , 
		the physical activity level is 'Physical Activity Level' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
